#ifndef ERROR_CODE_H
#define ERROR_CODE_H

enum ERROR_CODE	{
		MCF_SUCCESS, 
		MCF_ERROR_PARALLEL_EDGE,
		MCF_ERROR_BAD_INBALANCE,
		MCF_ERROR_NEGATIVE_EDGE_COST,
		MCF_ERROR_NO_FEASEABLE_SOLUTION,
};

#endif
